#!/usr/bin/env bash
# ~/.bash_profile - sourced only when user completes their login prompt 

# env variables
export EDITOR='vim'
export VISUAL='vim'
export BROWSER='chromium'
export HISTCONTROL=ignoreboth:erasedups

export NO_AT_BRIDGE=1 # disable accessibity features
export QT_STYLE_OVERRIDE=kvantum
export FZF_DEFAULT_COMMAND="rg --files --follow --no-ignore-vcs --hidden -g '!{**/node_modules/*,**/.git/*}'"
export LC_ALL="en_US.utf-8"

# path - search for executables in these directories
export PATH=/opt/texlive/2022/bin/x86_64-linux:$PATH
export PATH=$PATH:$HOME/.local/bin/
export PATH=$PATH:$HOME/.local/bin/managers

export GOPATH=$HOME/.go # golang user settings
export PATH=$PATH:/usr/local/go/bin # golang runtime binaries
export PATH=$PATH:$GOPATH/bin # user binaries

# xdg base directories
export XDG_CONFIG_HOME=$HOME/.config # user configurations 
export XDG_DATA_HOME=$HOME/.local/share # user data 
export XDG_STATE_HOME=$HOME/.local/state # persistant state
export XDG_CACHE_HOME=$HOME/.cache # cached data
 
# XDG_RUNTIME_DIR env not set -- https://www.reddit.com/r/voidlinux/comments/m74p4g/xdg_runtime_dir_environment_variable/
sudo mkdir -p /run/user/$(id -u)
sudo chmod -R 700 /run/user/$(id -u)
sudo chown -R 1000:1000 /run/user/$(id -u)
export XDG_RUNTIME_DIR=/run/user/$(id -u)

# font configuration
export FREETYPE_PROPERTIES=“truetype:interpreter-version=38” # Subpixel hinting mode can be chosen by setting the right TrueType interpreter version.  

# merge multiple clipboards into one persistent clipboard
export CM_SELECTION="clipboard"
export CM_DEBUG=0
export CM_OUTPUT_CLIP=0
export CM_MAX_CLIPS=20

if [ -n "$BASH_VERSION" ] && [ -f $HOME/.bashrc ];then
    source $HOME/.bashrc
fi

