#!/usr/bin/env bash
# ~/.xinitrc - executed by startx (run your window manager here)

# merge in defaults and keymaps
userresources=$HOME/.Xresources
# usermodmap=$HOME/.Xmodmap

[[ -f "$userresources" ]] && xrdb -merge "$userresources"
# [[ -f "$usermodmap" ]] && xmodmap "$usermodmap"

# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#   [ -x "$f" ] && . "$f"
#  done
#  unset f
# fi

# exec connman w/ cmst 	# network 
# exec ...   	# bluetooth
# exec dunst	# notifications
# exec tlp 		# power
# exec ... 		# polkit? 

xrdb -load ~/.Xresources # set dotfile configs for x client applications
xset r rate 200 25 # speed up repeat-key-delay (in milliseconds w/ default 660) and repeat rate (w/ default 25)

exec dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus &
# why did i have to run ^ in my shell for playerctl daemon to work?

pipewire & # backend audio 
pipewire-pulse & # integrate pulseaudio compatible clients with pipewire
playerctld daemon &

sxhkd -c $HOME/.config/sxhkd/sxhkdrc & # keyboard shortcuts ($PATH w/ scripts must be loaded before sxhkd)
clipmenud & # clipboard manager

exec start-statusbar.sh & # custom status bar
exec undocked.sh & # setup internal monitor & wallpaper
exec dwm

